module.exports = {
  GAME_STARTED: 'GAME_STARTED',
  GAME_FINISHED: 'GAME_FINISHED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  FORBIDDEN: 'FORBIDDEN',
  NEXT_STEP: 'NEXT_STEP',
  PICK_FIELD: 'PICK_FIELD',
};
